import { useEffect, useMemo, useState } from 'react'
import { addDoc, collection, getDocs, serverTimestamp } from 'firebase/firestore'
import { ArrowLeft, Brain, Save, TrendingDown, TrendingUp } from 'lucide-react'
import { db } from '../firebase'

function runTree(node, features){ if(node.leaf!==undefined) return node.leaf; return features[node.feature] <= node.threshold ? runTree(node.left,features) : runTree(node.right,features) }
function predict(model,features){ const votes=model.trees.map(t=>runTree(t,features)); const counts=[0,0,0]; votes.forEach(v=>counts[v]++); const index=counts.indexOf(Math.max(...counts)); return {label:model.classes[index],confidence:Math.round(counts[index]/model.trees.length*100)} }

export default function AcademicRecords({user,onBack}){
 const [students,setStudents]=useState([]),[subjects,setSubjects]=useState([]),[marks,setMarks]=useState([]),[attendance,setAttendance]=useState([]),[studentId,setStudentId]=useState(''),[subjectId,setSubjectId]=useState(''),[att,setAtt]=useState(''),[mark,setMark]=useState(''),[model,setModel]=useState(null),[msg,setMsg]=useState('')
 useEffect(()=>{Promise.all([getDocs(collection(db,'students')),getDocs(collection(db,'subjects')),getDocs(collection(db,'marks')),getDocs(collection(db,'attendance')),fetch('/model.json').then(r=>r.json())]).then(([a,b,c,d,m])=>{setStudents(a.docs.map(x=>({id:x.id,...x.data()})));setSubjects(b.docs.map(x=>({id:x.id,...x.data()})));setMarks(c.docs.map(x=>({id:x.id,...x.data()})));setAttendance(d.docs.map(x=>({id:x.id,...x.data()})));setModel(m)}).catch(e=>setMsg(e.message))},[])
 const student=students.find(x=>x.id===studentId)
 const studentMarks=useMemo(()=>marks.filter(x=>x.studentId===studentId),[marks,studentId])
 const studentAttendance=useMemo(()=>attendance.filter(x=>x.studentId===studentId),[attendance,studentId])
 const avgMarks=studentMarks.length?studentMarks.reduce((a,x)=>a+Number(x.value||0),0)/studentMarks.length:Number(mark||0)
 const avgAttendance=studentAttendance.length?studentAttendance.reduce((a,x)=>a+Number(x.value||0),0)/studentAttendance.length:Number(att||0)
 const ordered=[...studentMarks].sort((a,b)=>{const aa=a.createdAt?.seconds||0,bb=b.createdAt?.seconds||0;return aa-bb})
 const trend=ordered.length>1?Number(ordered.at(-1).value)-Number(ordered[0].value):0
 const missed=Math.max(0,5-studentMarks.length)
 const prediction=model&&studentId&&avgAttendance&&avgMarks?predict(model,[avgAttendance,avgMarks,trend,missed]):null
 const save=async(type,value)=>{if(!studentId||!value)return setMsg('Select a student and enter a value.');try{const subject=subjects.find(x=>x.id===subjectId);await addDoc(collection(db,type),{studentId,studentName:student?.name||'',subjectId,subjectName:subject?.name||'',value:Number(value),type,recordedBy:user?.uid||'',createdAt:serverTimestamp()});if(type==='marks'){setMarks(x=>[...x,{studentId,value:Number(value),createdAt:{seconds:Date.now()/1000}}]);setMark('')}else{setAttendance(x=>[...x,{studentId,value:Number(value),createdAt:{seconds:Date.now()/1000}}]);setAtt('')}setMsg(`${type} saved.`)}catch(e){setMsg(e.message)}}
 const savePrediction=async()=>{if(!prediction)return;try{await addDoc(collection(db,'predictions'),{studentId,studentName:student?.name||'',riskLevel:prediction.label,confidence:prediction.confidence,features:{attendance:Number(avgAttendance.toFixed(2)),averageMarks:Number(avgMarks.toFixed(2)),recentTrend:Number(trend.toFixed(2)),missedAssessments:missed},model:'Random Forest',createdAt:serverTimestamp(),generatedBy:user?.uid||''});setMsg('AI prediction saved.')}catch(e){setMsg(e.message)}}
 return <main className="min-h-screen bg-slate-950 text-white"><nav className="border-b border-slate-800 bg-slate-900 p-5"><div className="mx-auto flex max-w-7xl justify-between"><div><h1 className="font-bold">Attendance & Marks</h1><p className="text-xs text-slate-500">Academic records and trained Random Forest risk prediction</p></div><button onClick={onBack} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2"><ArrowLeft size={16}/>Dashboard</button></div></nav><section className="mx-auto max-w-7xl p-6">{msg&&<p className="mb-5 rounded-lg bg-slate-900 p-3 text-sm text-slate-300">{msg}</p>}<div className="grid gap-6 lg:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5 lg:col-span-2"><h2 className="mb-5 font-semibold">Record student performance</h2><select value={studentId} onChange={e=>{setStudentId(e.target.value);setAtt('');setMark('')}} className="mb-3 w-full rounded-lg bg-slate-950 p-3"><option value="">Select student</option>{students.map(x=><option key={x.id} value={x.id}>{x.name} · {x.admissionNumber||x.rollNo||''}</option>)}</select><select value={subjectId} onChange={e=>setSubjectId(e.target.value)} className="mb-5 w-full rounded-lg bg-slate-950 p-3"><option value="">Select subject</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name} · {x.code}</option>)}</select><div className="grid gap-4 sm:grid-cols-2"><Box title="Attendance %" value={att} set={setAtt} save={()=>save('attendance',att)}/><Box title="Marks %" value={mark} set={setMark} save={()=>save('marks',mark)}/></div></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex items-center gap-2 text-emerald-400"><Brain/><h2 className="font-semibold">AI Risk Prediction</h2></div>{studentId?<><p className="mt-5 text-center text-sm text-slate-400">{student?.name}</p><p className="mt-2 text-center text-4xl font-bold">{prediction?.label||'—'}</p>{prediction&&<><p className="mt-2 text-center text-xs text-slate-500">Model confidence: {prediction.confidence}%</p><div className="mt-6 space-y-3 text-sm"><p>Attendance <b>{avgAttendance.toFixed(1)}%</b></p><p>Average marks <b>{avgMarks.toFixed(1)}%</b></p><p className="flex items-center gap-2">Recent trend <b>{trend>0?'+':''}{trend.toFixed(1)}%</b>{trend>0?<TrendingUp size={16}/>:trend<0?<TrendingDown size={16}/>:null}</p><p>Missed assessments <b>{missed}</b></p></div><p className="mt-5 text-sm text-slate-400">{prediction.label==='High'?'Improve attendance, review weak subjects and seek academic support.':prediction.label==='Medium'?'Monitor attendance and upcoming assessments closely.':'Current academic indicators are comparatively stable.'}</p><button onClick={savePrediction} className="mt-5 w-full rounded-lg bg-emerald-500 py-2.5 font-semibold text-slate-950">Save AI Prediction</button></>}</>:<p className="mt-8 text-sm text-slate-500">Select a student to calculate risk.</p>}</div></div></section></main>
}
function Box({title,value,set,save}){return <div className="rounded-xl border border-slate-800 p-4"><p className="mb-2 text-sm text-slate-400">{title}</p><input type="number" min="0" max="100" value={value} onChange={e=>set(e.target.value)} className="mb-3 w-full rounded-lg bg-slate-950 p-3"/><button onClick={save} className="inline-flex w-full justify-center gap-2 rounded-lg bg-emerald-500 p-2.5 font-semibold text-slate-950"><Save size={16}/>Save</button></div>}
