import { useState } from 'react'
import { BarChart3, Brain, Building2, CalendarDays, GraduationCap, LayoutDashboard, LogOut, School, Users, ClipboardCheck, Link2 } from 'lucide-react'
import Login from './pages/auth/Login'
import Branches from './pages/admin/Branches'
import Programs from './pages/admin/Programs'
import AcademicYears from './pages/admin/AcademicYears'
import ClassesSections from './pages/admin/ClassesSections'
import StudentsEnrollments from './pages/admin/StudentsEnrollments'
import Assignments from './pages/admin/Assignments'
import AdminManagement from './pages/admin/AdminManagement'
import AcademicRecords from './pages/AcademicRecords'
import Analytics from './pages/Analytics'
import RoleDashboard from './pages/RoleDashboard'
import { logoutUser } from './services/authService'
const modules=[
{title:'Branches',description:'Manage institute branches and locations.',icon:Building2,page:'branches'},
{title:'Programs',description:'Manage school, junior college and degree programs.',icon:GraduationCap,page:'programs'},
{title:'Academic Years',description:'Set up academic years and sessions.',icon:CalendarDays,page:'academic-years'},
{title:'Classes & Sections',description:'Organize classes, sections and academic structure.',icon:LayoutDashboard,page:'classes-sections'},
{title:'Students & Enrollments',description:'Manage student profiles and academic-year enrollment.',icon:Users,page:'students'},
{title:'Teachers',description:'Manage teacher profiles.',icon:Users,page:'teachers'},
{title:'Subjects',description:'Create subjects and codes.',icon:School,page:'subjects'},
{title:'Teacher Assignments',description:'Connect teachers, subjects and classes.',icon:Link2,page:'assignments'},
{title:'Attendance & Marks',description:'Record performance and generate AI risk insight.',icon:ClipboardCheck,page:'records'},
{title:'Analytics',description:'View institute metrics and risk distribution.',icon:BarChart3,page:'analytics'}]
function App(){const[page,setPage]=useState('home'),[user,setUser]=useState(null);const login=u=>{setUser(u);setPage('dashboard')};const logout=async()=>{await logoutUser();setUser(null);setPage('home')};if(page==='login')return <Login onLogin={login} onBack={()=>setPage('home')}/>;if(page==='branches')return <Branches onBack={()=>setPage('dashboard')}/>;if(page==='programs')return <Programs onBack={()=>setPage('dashboard')}/>;if(page==='academic-years')return <AcademicYears onBack={()=>setPage('dashboard')}/>;if(page==='classes-sections')return <ClassesSections onBack={()=>setPage('dashboard')}/>;if(page==='students')return <StudentsEnrollments onBack={()=>setPage('dashboard')}/>;if(page==='assignments')return <Assignments onBack={()=>setPage('dashboard')}/>;if(['teachers','subjects'].includes(page))return <AdminManagement type={page} onBack={()=>setPage('dashboard')}/>;if(page==='records')return <AcademicRecords user={user} onBack={()=>setPage('dashboard')}/>;if(page==='analytics')return <Analytics onBack={()=>setPage('dashboard')}/>;if(page==='role')return <RoleDashboard user={user} onBack={()=>setPage('dashboard')}/>;if(page==='dashboard')return <Dashboard user={user} onLogout={logout} onNavigate={setPage}/>;return <Landing onSignIn={()=>setPage('login')}/>}
function Landing({onSignIn}){return <main className="min-h-screen bg-slate-950 text-white"><nav className="mx-auto flex max-w-7xl justify-between px-6 py-5"><Brand/><button onClick={onSignIn} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Sign In</button></nav><section className="mx-auto max-w-7xl px-6 py-20"><div className="max-w-4xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full bg-emerald-400/10 px-3 py-2 text-sm text-emerald-300"><Brain size={16}/>AI-powered academic insights</div><h1 className="text-5xl font-bold leading-tight sm:text-6xl">Smarter institute management. <span className="text-emerald-400">Better student outcomes.</span></h1><p className="mt-6 text-lg leading-8 text-slate-400">Manage academic structure, students, teachers, attendance, marks, analytics and student risk prediction in one working prototype.</p><button onClick={onSignIn} className="mt-8 rounded-xl bg-emerald-500 px-5 py-3 font-semibold text-slate-950">Open Dashboard</button></div></section></main>}
function Dashboard({user,onLogout,onNavigate}){const role=user?.role||'user';const admin=role==='admin';return <main className="min-h-screen bg-slate-950 text-white"><nav className="border-b border-slate-800 bg-slate-900/80 px-6 py-4"><div className="mx-auto flex max-w-7xl items-center justify-between"><Brand/><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-sm">{user?.name||user?.email}</p><p className="text-xs text-emerald-400">{role}</p></div><button onClick={onLogout} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm"><LogOut size={16}/>Logout</button></div></div></nav><section className="mx-auto max-w-7xl px-6 py-8"><p className="text-sm text-emerald-400">{role} dashboard</p><h1 className="mt-2 text-3xl font-bold">Welcome, {user?.name||'User'}.</h1><p className="mt-2 text-slate-400">{admin?'Manage institute data and academic performance.':'Open your academic workspace to view or record performance.'}</p>{admin?<><div className="my-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Students"/><Stat label="Teachers"/><Stat label="Programs"/><Stat label="AI Predictions"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map(m=><Module key={m.title} {...m} onClick={()=>onNavigate(m.page)}/>)}</div></>:<div className="mt-8 max-w-md"><Module title="Academic Workspace" description="Open the role-specific academic dashboard." icon={ClipboardCheck} onClick={()=>onNavigate('role')}/></div>}</section></main>}
function Stat({label}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-bold">—</p></div>}
function Module({title,description,icon:Icon,onClick}){return <button onClick={onClick} className="group rounded-2xl border border-slate-800 bg-slate-900 p-5 text-left hover:border-emerald-400/40"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-slate-800 text-emerald-400"><Icon size={21}/></div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><p className="mt-4 text-xs text-emerald-400">Open →</p></button>}
function Brand(){return <div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500 text-slate-950"><GraduationCap size={23}/></div><div><p className="text-lg font-bold">EduSmart AI</p><p className="text-xs text-slate-400">Institute Management System</p></div></div>}
export default App
